# Site settings
name: Devesh Anand
title: Devesh Anand
email: contactdeveshanand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Devesh Anand. This is my online haven where I share my thoughts 
  and my work. 
  I write my blog from time to time.
#baseurl: "/Read-Only-Jekyll-Theme" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "https://deveshanand.com" # the base hostname & protocol for your site
twitter_username: deveshanand18
github_username:  devesh-anand

author:
  name: Devesh Anand Srivastava
  email: *email
  twitter: deveshanand18

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      comments: "true"

plugins:
  - jekyll-analytics
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed


jekyll_analytics:
  GoogleAnalytics:
    id: UA-163837086-1
    anonymizeIp: false

# Build settings
markdown: kramdown

exclude:
- path


staticman_url: https://deveshblogcomments.herokuapp.com/v2/entry/devesh-anand/devesh-anand.github.io/master/comments

reCaptcha:
  siteKey: 6Lf8wvMUAAAAAMwjwyghEI3RgCqaIvzkM2S4G2hc
  secret: ZiiV4VAWoctTT92vPQde//ujjqb1rZVC074L7swNKxpbIZ0XrhukloIUj4FL42i3qE2owFLAbvKV7U3RiiYAnYA0975v81Qh7yX3jiLrCYxLrr5MPhlee3lxcE61KyLG2oMRd84vIpVZg4kMh4fNFI+qRXIPLNo2VIYQc3nj7emRW4r6j+BGIjEztvM+wQI12mzrjVjg9TPMw6wvFL32OsAOZwwwxJMVyySgucXhN9zSgZ9TD1td5L9uGM9hJV4XymfTdcm5kfPp54y964X3Cu8f8VLS6y1ZOzEXUszLoQY7J3caeg9kX73PcX+o/z6f1Yr5RlEe8qZiRB34R2I3cvo86T+xbIYAW3ZeK7wQPlmY6iW0pftDFVk2dHEc5H3zoYuVRJ+EV41HbbsRnX7HxTXgMTne6v05hpY/97bZxDr02p2T8fh1HyQ+ujLcLVv6CIbDPv/Jss/dqAJwTtT/XzgorUx8wmBe49dt3Gx+E8JQhc8C+Oow87L7AUfc3osK7gWnpSY96spdiDJcjDDyQv+dwE11AVHZX8uasr3lmJn3wXDFq+0GT6jRET8+fZmpHEuXpomZQ3RF6PlcQ0Gpcjhiedjz+0YpEnISdqzw3r7EK/1uGosom3Z2/mzV42i6AtqU3+tCDgLMuLk4tAXu0NL/Gu8einndqaira6s0zw4=
